import Link from "next/link"
import { projects, links } from "@/lib/site-content"
import { FillImage } from "@/components/wii/wii-image"
export const metadata = { title: "Engineering Projects · Hans Vador", description: "Robotics, mechanical design, and embedded systems projects by Hans Vador." }
export default function Projects() { return <div className="project-document fixed inset-0 overflow-y-auto">
<header className="portfolio-header"><Link href="/" className="wii-title text-xl">Hans Vador</Link><nav className="flex gap-4 text-sm" aria-label="Portfolio navigation"><Link href="/">Wii menu</Link><a href={links.linkedin}>LinkedIn</a><a href={`mailto:${links.email}`}>Contact</a></nav></header>
<main className="mx-auto max-w-6xl px-5 py-10 sm:py-16"><p className="text-sm uppercase tracking-[0.18em] text-[var(--wii-blue-deep)]">Selected engineering work</p><h1 className="wii-title mt-3 text-4xl sm:text-5xl">From hardware to working systems.</h1><p className="mt-4 max-w-2xl leading-relaxed">I’m Hans, a Mechanical & Computer Engineering student at the University of Michigan. Explore what I built, the engineering decisions behind it, and the results.</p>
<div className="mt-10 grid gap-6 md:grid-cols-2">{projects.map((p, i) => <article key={p.id} className="wii-plate overflow-hidden"><div className="relative aspect-[16/10]"><FillImage src={p.image} alt={p.title} sizes="(max-width: 768px) 100vw, 560px" priority={i === 0} /></div><div className="p-6"><p className="text-xs uppercase tracking-widest text-[var(--wii-blue-deep)]">{i === 0 ? "Robotics · Team project" : "Embedded systems · Personal project"}</p><h2 className="wii-title mt-2 text-2xl">{p.title}</h2><p className="mt-3 leading-relaxed">{p.shortDescription}</p><div className="mt-4 flex flex-wrap gap-2">{p.tags.map(t=><span className="wii-pill" key={t}>{t}</span>)}</div><Link className="wii-oval mt-6 inline-flex px-5 py-3 text-sm" href={i === 0 ? "/projects/hexapod" : "/projects/volume-control"}>View project →</Link></div></article>)}</div>
</main></div> }
